module.exports = [
  { intent: 'projects',     agent: 'project-manager', description: 'project status, tasks, blockers, whats next, Shrody/OnlyHuman/Caligulas/JARVIS progress' },
  { intent: 'builder',      agent: 'builder',         description: 'build, fix, create, code, deploy, make something technical' },
  { intent: 'ideas',        agent: 'ideas',           description: 'capture ideas, park thoughts, remember something for later' },
  { intent: 'finance',      agent: 'finance',         description: 'revenue, money, Stripe, payments, how much earned' },
  { intent: 'ops',          agent: 'ops',             description: 'server status, deployment, is site up or down, Vercel errors, crashes' },
  { intent: 'caligulas',    agent: 'caligulas',       description: 'Caligulas post creation, counter-award content, monthly posts' },
  { intent: 'comfyui',      agent: 'comfyui',         description: 'generate images, create visuals, artwork for any project' },
  { intent: 'marketing',    agent: 'marketing',       description: 'copywriting, captions, emails, influencer briefs, directory submissions, post drafts for any product' },
  { intent: 'nutrition',    agent: 'nutritionist',    description: 'food, meals, nutrition advice, energy, what to eat, food logging' },
  { intent: 'fitness',      agent: 'trainer',         description: 'exercise, workouts, fitness, activity logging, training plans, movement' },
  { intent: 'psych',        agent: 'psychologist',    description: 'mental health, stress, feelings, journaling, venting, emotional support, reflection' },
  { intent: 'security',     agent: 'security',        description: 'Mac security, suspicious processes, system integrity' },
  { intent: 'distribution', agent: 'distribution',    description: 'influencer research, outreach DMs, NDIS directory submissions, TikTok strategy, creator briefs' },
  { intent: 'seo',          agent: 'seo',             description: 'SEO audit, AIO optimisation, meta tags, content gaps, AI search visibility for Shrody' },
  { intent: 'competitor',   agent: 'competitor',      description: 'market scans, competitive analysis, positioning, trend monitoring for any product' },
  { intent: 'general',      agent: null,              description: 'everything else, conversation, questions, advice' },
];
